/* eslint-disable */
require('./accept')
require('./arrow')
require('./budget')
require('./calendar')
require('./client')
require('./close')
require('./copy')
require('./delete')
require('./filters')
require('./invoice')
require('./menu')
require('./pdf')
require('./reject')
